<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>TestResponse</code>
 */
class TestResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 nums = 3;</code>
     */
    private $nums = 0;
    /**
     * <code>int32 memberId = 4;</code>
     */
    private $memberId = 0;

    public function __construct() {
        \GPBMetadata\Test::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 nums = 3;</code>
     */
    public function getNums()
    {
        return $this->nums;
    }

    /**
     * <code>int32 nums = 3;</code>
     */
    public function setNums($var)
    {
        GPBUtil::checkInt32($var);
        $this->nums = $var;
    }

    /**
     * <code>int32 memberId = 4;</code>
     */
    public function getMemberId()
    {
        return $this->memberId;
    }

    /**
     * <code>int32 memberId = 4;</code>
     */
    public function setMemberId($var)
    {
        GPBUtil::checkInt32($var);
        $this->memberId = $var;
    }

}

